version: '3.7'
services:
  postgres:
    image: postgres:14
    container_name: lab4-dev-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: credits
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: lab4-dev-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: lab4-dev-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio124
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
