# Конфигурация веб-сервера для Docker
ServiceHost = "0.0.0.0"
ServicePort = 8080

# Конфигурация базы данных PostgreSQL
[database]
host = "postgres"
port = 5432
user = "myuser"
password = "mypassword"
dbname = "credits"
sslmode = "disable"

# Конфигурация MinIO
[minio]
endpoint = "nginx:9000"
public_endpoint = "localhost:9000"
access_key = "minio"
secret_key = "minio124"
use_ssl = false
bucket_name = "credits"

# Конфигурация JWT
[jwt]
secret_key = "your-secret-key-change-this-in-production"
expires_in = "24h"  # Время жизни токена (24 часа)

# Конфигурация Redis
[redis]
host = "redis"
port = 6379
password = "password"
db = 0
dial_timeout = "10s"
read_timeout = "10s"

